import Logo2 from './Logo2.png';
import eyes from './eyes.png';
import eyesclosed from './eyesclosed.png';
import facebook from './facebook-icon.png';
import google from './google-icon.png';
import Cards from './Cards .png';
import Add from './Add.png';
import Min from './min.png';
import Plus from './plus.png';
export {Logo2, eyes, eyesclosed, Cards, facebook, google, Add, Min, Plus};
